### ISSUE TITLE
test all forms for required fields

### ISSUE THREAD

**Issue by brunosardinepi** [brunosardinepi/pagefund#292]

**Comment by dmortazavi** [comment]
Tested page creation form. All required fields prompted an entry before allowing me to submit

Tested campaign creation. No goal requirement or end date requirement. I think these need to be listed as requirements. For sure need end date, otherwise, a general campaign is no diff than a page

Tested sign up. All required fields prompted an entry before allowing me to submit

Tested donation. all required fields prompted an entry. without selecting an amount, i did not get a prompt, however, nothing happened when i clicked submit so it served the correct purpose.

**Comment by brunosardinepi** [comment]
fixed the issues on campaign creation
