### ISSUE TITLE
determine what happens when saving a card if it already exists

### ISSUE THREAD

**Issue by brunosardinepi** [brunosardinepi/pagefund#473]
Does it overwrite the existing one (exp date, cvv) or does it ignore it and do a one-time charge?

**Comment by dmortazavi** [comment]
What happens if there is a saved card and a user types in that same (or different) card when making a donation? - the manually typed in card should take precedence. if someone types something, thats what they want 

what happens if someone tried to save the same card? - nothing. we should recognize they already have it and do nothing

what happens if someone tried to save the same card but it has a diff cvv or exp date? - save both cards

**Comment by brunosardinepi** [comment]
stripe sees two cards with the same 16 digits as identical regardless of exp date or cvv. users will have to update their cc info in their profile instead of overwriting it on the donation page. we're ok with this for now.
